import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Valeries Factory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.nav}>
          <div>
            <Link href="/">
            <Image
              src="/valeriesLogo.png"
              alt="Valeries"
              width={60}
              height={60}
              priority
            />

            </Link>
          </div>
          <div className={styles.list}>
            <ul>
              <li><Link href="/artists">Artists</Link></li>
              <li><a href="">Exhibitions</a></li>
              <li><a href="">Art Fairs</a></li>
              <li><a href="">Info</a></li>
              <li><a href="">Contact</a></li>
            </ul>
          </div>
          <div>
          </div>
        </div>

        {children}

        <div className={styles.footer}>
          <div>
            <p>
              Instagram
            </p>
          </div>
          <div>
            <p>
              LinkedIn
            </p>
          </div>
          <div>
            <p>
              Twitter
            </p>
          </div>
          <div>
            <p>
              Email
            </p>
          </div>
        </div>
        
        </body>
    </html>
  );
}
