import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Link from "next/link";
import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Valeries Factory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.nav}>
          <div>
            <Link href="/">
            <Image
              src="/valeriesLogo.png"
              alt="Valeries"
              width={60}
              height={60}
              priority
            />

            </Link>
          </div>
          <div className={styles.list}>
            <ul>
              <li><Link href="/artists">Artistas</Link></li>
              <li><Link href="/exhibitions">Exhibiciones</Link></li>
              <li><Link href="/contact">Contacto</Link></li>
            </ul>
          </div>
          <div>
          </div>
        </div>

        {children}

        <div className={styles.footer}>
          <p className={styles.title}>Manifesto</p>

          <div className={styles.contentSection} style={{borderTop: '0px solid #ffffff', marginTop: '1rem'}}>
            <p>
            Valerie es una galería de arte contemporáneo dirigida por Jimena Lusi, Xul Jan y Sandro Guevara. Es un espacio de cruce de lenguajes teniendo como núcleo las artes visuales, que pondera el trabajo colaborativo entre artistas, diseñadores, músicxs, curadores y gestores. Nos excitan los desafíos y lxs artistas apasionadxs, la moda y el futuro, las obras que  auguran ese espíritu que ama los días de sol, las girl-girls, las boy girls, los girl-boys y los boy-boys. El punk se relaciona con la contracultura, el decolonialismo y la rebelión juvenil; es nuestra utopía que tiene objetivos múltiples
            es proyectar una imagen de potencialidad y posibilidad
            en nombre de otro tiempo y otro lugar, socavando el tejido de la realidad.
            Una imagen intermedial del futuro,
            Negamos el presente que nos entristece.
            Nuestrx organismo como una ilegalidad,
            ninguna legalidad excepto el placer.
            Nuestra factoría. 

            </p>
          </div>
          <div className={styles.contentSection} style={{borderTop: '1px solid #ffffff'}}>
            <p className={styles.subtitle}>
              Artistas representados
            </p>
            <p>
              Alvaro Godoy -
              Elias Leiro -
              Facundo Belen -
              Facundo Jesus Lugea -
              Fanny Diaz -
              Franco Palioff -
              Frenetik Void -
              Julieta Proto Boca -
              Leonardo Sanchez -
              Marco Pimentel -
              Maruts Ballet -
              Matias Tomas -
              Sofia Castro -
              Tomo Cabrera -
              Trinidad Metz Brea
              Valentina Quintero
              

              </p>
          </div>
          <Link href="/">
          <Image
                  src="/valeriesLogoWhite.png"
                  width={0}
                  height={0}
                  sizes="100vw"
                  style={{ width: '100%', height: 'auto', maxWidth: '15rem', paddingTop: '5rem' }}
                  alt="Picture of the author"
          />
          </Link>
        </div>
        </body>
    </html>
  );
}
